import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import localFont from "next/font/local";
import 'easymde/dist/easymde.min.css'
import NavBar from "@/components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const libertinusMonoFont = localFont({
  src: "../../fonts/LibertinusKeyboard-Regular.ttf",
  variable: "--font-libertinus-mono",
  subsets: ["latin"],
});

const storyScript = localFont({
  src: "../../fonts/StoryScript-Regular.ttf",
  variable: "--font-storyscript",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${libertinusMonoFont.variable} ${storyScript.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
